# -*- coding: utf-8 -*-
"""BIKE RIDE ML .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ilo3wjdi7HHf1oY9YYT8NoOd3-OunSpL
"""

!pip install holidays

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from datetime import datetime
import holidays
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error as mae
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.ensemble import RandomForestRegressor

print("All libraries imported successfully ✅")

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Load the dataset
# 👇 Change the path if your file is in a different folder
df = pd.read_csv('/content/drive/MyDrive/ola.csv')

print("Shape:", df.shape)
df.head()

print("=== Dataset Info ===")
df.info()

print("\n=== Statistics ===")
df.describe().T

# Convert datetime column
df['datetime'] = pd.to_datetime(df['datetime'])

# Extract hour (time), day, month, year
df['time']  = df['datetime'].dt.hour
df['day']   = df['datetime'].dt.day
df['month'] = df['datetime'].dt.month
df['year']  = df['datetime'].dt.year

# Weekday: 1 = Weekday (Mon-Fri), 0 = Weekend
def weekend_or_weekday(year, month, day):
    try:
        d = datetime(year, month, day)
        return 0 if d.weekday() > 4 else 1
    except:
        return np.nan

df['weekday'] = df.apply(
    lambda x: weekend_or_weekday(x['year'], x['month'], x['day']), axis=1
)

# AM or PM: 0 = AM, 1 = PM
df['am_or_pm'] = df['time'].apply(lambda x: 1 if x > 11 else 0)

# Holiday: 1 = Holiday, 0 = Not
india_holidays = holidays.country_holidays('IN')
df['date'] = df['datetime'].dt.date.astype(str)
df['holidays'] = df['date'].apply(
    lambda x: 1 if india_holidays.get(x) else 0
)

print("New columns added ✅")
df.head()

# Drop datetime, date (already extracted)
# Drop registered (data leakage - too correlated with count)
# Drop time (already have am_or_pm)
df.drop(['datetime', 'date', 'registered', 'time'], axis=1, inplace=True)

print("Remaining columns:", df.columns.tolist())
df.head()

features = ['day', 'month']

plt.subplots(figsize=(15, 5))
for i, col in enumerate(features):
    plt.subplot(1, 2, i + 1)
    df.groupby(col).mean()['count'].plot()
    plt.title(f'Average Ride Count by {col}')
    plt.xlabel(col)
    plt.ylabel('Avg Count')
plt.tight_layout()
plt.show()

features = ['season', 'weather', 'holidays', 'am_or_pm', 'year', 'weekday']

plt.subplots(figsize=(20, 10))
for i, col in enumerate(features):
    plt.subplot(2, 3, i + 1)
    df.groupby(col).mean()['count'].plot.bar()
    plt.title(f'Avg Ride Count by {col}')
    plt.xlabel(col)
    plt.ylabel('Avg Count')
plt.tight_layout()
plt.show()

# Distribution plots
features = ['temp', 'windspeed']
plt.subplots(figsize=(15, 5))
for i, col in enumerate(features):
    plt.subplot(1, 2, i + 1)
    sb.histplot(df[col], kde=True)
    plt.title(f'Distribution of {col}')
plt.tight_layout()
plt.show()

# Box plots
features = ['windspeed', 'humidity', 'casual', 'count']
plt.subplots(figsize=(15, 10))
for i, col in enumerate(features):
    plt.subplot(2, 2, i + 1)
    sb.boxplot(df[col])
    plt.title(f'Boxplot of {col}')
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 8))
sb.heatmap(df.corr() > 0.8, annot=True, cbar=False, cmap='coolwarm')
plt.title('Highly Correlated Features (> 0.8)')
plt.show()

print("Before removing outliers:", df.shape)

df = df[(df['windspeed'] < 32) & (df['humidity'] > 0)]

print("After removing outliers:", df.shape)

features = df[[
    'season', 'weather', 'temp', 'humidity', 'windspeed',
    'day', 'month', 'year', 'weekday', 'am_or_pm', 'holidays'
]]
target   = df['count'].values

X_train, X_val, Y_train, Y_val = train_test_split(
    features, target, test_size=0.1, random_state=22
)

print("Training size:", X_train.shape)
print("Validation size:", X_val.shape)

# Normalize
scaler  = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val   = scaler.transform(X_val)

print("Data normalized ✅")

models = [
    LinearRegression(),
    Lasso(),
    Ridge(),
    RandomForestRegressor()
]

for model in models:
    model.fit(X_train, Y_train)

    train_preds = model.predict(X_train)
    val_preds   = model.predict(X_val)

    print(f"Model: {model.__class__.__name__}")
    print(f"  Training MAE   : {mae(Y_train, train_preds):.2f} bikes")
    print(f"  Validation MAE : {mae(Y_val,   val_preds):.2f} bikes")
    print()

# Best model = Random Forest
best_model = RandomForestRegressor()
best_model.fit(X_train, Y_train)

# --- CHANGE THESE VALUES TO TEST DIFFERENT SCENARIOS ---
sample = pd.DataFrame([{
    'season'   : 2,      # 1=Spring 2=Summer 3=Fall 4=Winter
    'weather'  : 1,      # 1=Clear 2=Mist 3=Light Rain 4=Heavy Rain
    'temp'     : 25.0,   # Temperature in Celsius
    'humidity' : 50.0,   # Humidity %
    'windspeed': 10.0,   # Wind speed
    'casual'   : 20,     # Approx casual users
    'day'      : 15,     # Day of month
    'month'    : 6,      # Month (6 = June)
    'year'     : 2012,   # Year
    'weekday'  : 1,      # 1=Weekday 0=Weekend
    'am_or_pm' : 1,      # 0=AM 1=PM
    'holidays' : 0,      # 0=No holiday 1=Holiday
}])

# Use only columns the model was trained on
sample = sample[features.columns]
sample_scaled = scaler.transform(sample)

prediction = best_model.predict(sample_scaled)

print(f"Predicted Bike Ride Requests: {int(prediction[0])} rides this hour")

# Multiple scenario predictions
scenarios = pd.DataFrame([
    # season, weather, temp, humidity, windspeed, day, month, year, weekday, am_or_pm, holidays

    {'season':2, 'weather':1, 'temp':35, 'humidity':40, 'windspeed':8,  'day':15, 'month':6,  'year':2012, 'weekday':1, 'am_or_pm':1, 'holidays':0},
    {'season':2, 'weather':1, 'temp':30, 'humidity':50, 'windspeed':10, 'day':10, 'month':7,  'year':2012, 'weekday':1, 'am_or_pm':0, 'holidays':0},
    {'season':1, 'weather':2, 'temp':15, 'humidity':65, 'windspeed':12, 'day':5,  'month':3,  'year':2012, 'weekday':1, 'am_or_pm':1, 'holidays':0},
    {'season':4, 'weather':3, 'temp':8,  'humidity':80, 'windspeed':18, 'day':20, 'month':12, 'year':2012, 'weekday':0, 'am_or_pm':0, 'holidays':0},
    {'season':4, 'weather':4, 'temp':3,  'humidity':95, 'windspeed':25, 'day':25, 'month':1,  'year':2012, 'weekday':0, 'am_or_pm':0, 'holidays':1},
    {'season':3, 'weather':1, 'temp':25, 'humidity':55, 'windspeed':9,  'day':8,  'month':9,  'year':2012, 'weekday':1, 'am_or_pm':1, 'holidays':0},
    {'season':2, 'weather':1, 'temp':32, 'humidity':45, 'windspeed':7,  'day':1,  'month':8,  'year':2012, 'weekday':0, 'am_or_pm':1, 'holidays':0},
    {'season':1, 'weather':3, 'temp':10, 'humidity':85, 'windspeed':20, 'day':18, 'month':2,  'year':2012, 'weekday':1, 'am_or_pm':0, 'holidays':0},

    # 🔥 HIGH DEMAND
    {'season':2, 'weather':1, 'temp':36, 'humidity':35, 'windspeed':5,
     'day':14, 'month':6, 'year':2012, 'weekday':0, 'am_or_pm':1, 'holidays':0},

    # ❄️ LOW DEMAND
    {'season':4, 'weather':4, 'temp':2, 'humidity':95, 'windspeed':30,
     'day':10, 'month':1, 'year':2012, 'weekday':1, 'am_or_pm':0, 'holidays':0},
])

labels = [
    "Hot Summer Afternoon (Weekday)",
    "Warm Summer Morning (Weekday)",
    "Mild Spring Evening (Weekday)",
    "Cold Winter Morning (Weekend)",
    "Heavy Rain Winter Holiday",
    "Clear Fall Afternoon (Weekday)",
    "Sunny Summer Weekend PM",
    "Light Rain Spring Morning",

    "Extreme Sunny Weekend PM ",
    "Heavy Rain Cold Morning "
]

# Predict all
scenarios_scaled = scaler.transform(scenarios[features.columns])
predictions = best_model.predict(scenarios_scaled).astype(int)

# Show results
results = pd.DataFrame({
    'Scenario'        : labels,
    'Predicted Rides' : predictions
})

print("=" * 60)
print("       BIKE RIDE REQUEST FORECAST - FINAL RESULTS")
print("=" * 60)
print(results.to_string(index=False))
print("=" * 60)

plt.figure(figsize=(14, 7))
colors = ['green' if p > 130 else 'orange' if p > 110 else 'red' for p in predictions]
bars = plt.bar(range(len(labels)), predictions, color=colors)

plt.xticks(range(len(labels)), labels, rotation=25, ha='right', fontsize=9)
plt.ylabel('Predicted Bike Ride Requests', fontsize=12)
plt.title('Bike Ride Request Forecast - Multiple Scenarios', fontsize=14, fontweight='bold')

# Add number on top of each bar
for bar, val in zip(bars, predictions):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 2,
             str(val), ha='center', va='bottom', fontweight='bold', fontsize=11)

plt.tight_layout()
plt.show()

print("\n🟢 Green = High Demand (>150) | 🟠 Orange = Medium (100-150) | 🔴 Red = Low (<100)")